#include <debug.h>
#include "hal_data.h"

FSP_CPP_HEADER
FSP_CPP_FOOTER

static volatile int g_uart7_tx_complete = 0;
static volatile int g_uart7_rx_complete = 0;

void debug_init()
{
	g_uart7.p_api->open(g_uart7.p_ctrl, g_uart7.p_cfg);

}


void uart7_callback(uart_callback_args_t * p_args)
{
    if (p_args->event == UART_EVENT_TX_COMPLETE)
    {
        g_uart7_tx_complete = 1;
    }
    else if (p_args->event == UART_EVENT_RX_COMPLETE)
    {
        g_uart7_rx_complete = 1;			
    }
}

static void uart7_wait_for_tx(void)
{
    while (!g_uart7_tx_complete);
    g_uart7_tx_complete = 0;
}

static void uart7_wait_for_rx(void)
{
    while (!g_uart7_rx_complete);
    g_uart7_rx_complete = 0;
}


int fputc(int ch, FILE * f)
{
	(void)f;


	g_uart7.p_api->write(g_uart7.p_ctrl, (uint8_t const * const)&ch, 1);
	

	uart7_wait_for_tx();
    
	return ch;
}

int fgetc(FILE *f)
{
	uint8_t ch;
	
	(void)f;


	g_uart7.p_api->read(g_uart7.p_ctrl, &ch, 1);
	
	uart7_wait_for_rx();

	{
		fputc(ch, NULL);

		if (ch == '\r')
		{
			fputc('\n', NULL);;
		}
	}
    
	return (int)ch;
}


void debug_led(void)
{
	bsp_io_level_t level = BSP_IO_LEVEL_LOW;
	g_ioport.p_api->pinWrite(g_ioport.p_ctrl, BSP_IO_PORT_04_PIN_00, level);
	level = !level;
}




///*******************************************************************************************************************//**
// * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
// * is called by main() when no RTOS is used.
// **********************************************************************************************************************/
//void hal_entry(void)
//{
//    /* TODO: add your own code here */
//    fsp_err_t err;
//    uint32_t a, b;


//    err = g_uart7.p_api->open(g_uart7.p_ctrl, g_uart7.p_cfg);

//    printf("www.100ask.net\r\n");

//    while (1)
//    {
//		printf("Please enter two number:\r\n");
//        scanf("%d%d", &a, &b);
//		printf("%d+%d=%d\r\n", a, b, a+b);
//    }

//#if BSP_TZ_SECURE_BUILD
//    /* Enter non-secure code */
//    R_BSP_NonSecureEnter();
//#endif
//}

///*******************************************************************************************************************//**
// * This function is called at various points during the startup process.  This implementation uses the event that is
// * called right before main() to set up the pins.
// *
// * @param[in]  event    Where at in the start up process the code is currently at
// **********************************************************************************************************************/
//void R_BSP_WarmStart (bsp_warm_start_event_t event)
//{
//    if (BSP_WARM_START_RESET == event)
//    {
//#if BSP_FEATURE_FLASH_LP_VERSION != 0

//        /* Enable reading from data flash. */
//        R_FACI_LP->DFLCTL = 1U;

//        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
//         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
//#endif
//    }

//    if (BSP_WARM_START_POST_C == event)
//    {
//        /* C runtime environment and system clocks are setup. */

//        /* Configure pins. */
//        R_IOPORT_Open(&g_ioport_ctrl, g_ioport.p_cfg);
//    }
//}

//#if BSP_TZ_SECURE_BUILD

//BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

///* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
//BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
//{

//}
//#endif
